version: '3.8'
services:
  server:
    image: ghcr.io/blopser/python-dev:slim
    environment:
      - PIP_REQUIREMENTS=jupyter requests
    volumes:
      - ./var/home:/home/user
      - ./app:/home/user/app
    command: jupyter lab --ip=0.0.0.0 --port=18888 --notebook-dir=.
    ports:
      - 18888:18888
    x-podman.uidmaps: ["0:1:1", "${UID:-1000}:0:1"]
    x-podman.gidmaps: ["0:1:1", "${UID:-1000}:0:1"]
