services:
  web:
    build:
      context: .
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - BASE_IMAGE=alpine
        - SYS_REQUIREMENTS=shadow
    command: python -c "import tqdm; print(tqdm)"
    environment:
      - PIP_REQUIREMENTS=tqdm gunicorn
    volumes:
      - ./venv:/home/user/app/venv
