services:
  nginx:
    build: .
    ports:
      - "8080:8081"
    user: ${UID}
    environment:
      - BASE_IMAGE=latest
      - NGINX_PORT=8081
    volumes:
      - './static:/var/www/static'
      - './conf/default-wsgi.conf.template:/etc/nginx/templates/default.conf.template'

  web:
    image: python:3.12-alpine3.20
    command: python3 -m http.server -b 0.0.0.0 8000 -d .
    ports:
      - "8000:8000"
